/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the Apache License, Version 2.0  (the "License"); you may not use this file
 * except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */


#ifndef FILE_3GPP_29_502_SMF_SEEN
#define FILE_3GPP_29_502_SMF_SEEN


enum pdu_session_application_error_e {
  PDU_SESSION_APPLICATION_ERROR_N1_SM_ERROR	= 1,
  PDU_SESSION_APPLICATION_ERROR_SNSSAI_DENIED = 2,
  PDU_SESSION_APPLICATION_ERROR_DNN_DENIED = 3,
  PDU_SESSION_APPLICATION_ERROR_PDUTYPE_DENIED = 4,
  PDU_SESSION_APPLICATION_ERROR_SSC_DENIED = 5,
  PDU_SESSION_APPLICATION_ERROR_SUBSCRIPTION_DENIED = 6,
  PDU_SESSION_APPLICATION_ERROR_DNN_NOT_SUPPORTED = 7,
  PDU_SESSION_APPLICATION_ERROR_PDUTYPE_NOT_SUPPORTED = 8,
  PDU_SESSION_APPLICATION_ERROR_SSC_NOT_SUPPORTED = 9,
  PDU_SESSION_APPLICATION_ERROR_HOME_ROUTED_ROAMING_REQUIRED = 10,
  PDU_SESSION_APPLICATION_ERROR_OUT_OF_LADN_SERVICE_AREA = 11,
  PDU_SESSION_APPLICATION_ERROR_N2_SM_ERROR = 12,
  PDU_SESSION_APPLICATION_ERROR_PRIORITIZED_SERVICES_ONLY = 13,
  PDU_SESSION_APPLICATION_ERROR_PDU_SESSION_ANCHOR_CHANGE = 14,
  PDU_SESSION_APPLICATION_ERROR_TARGET_MME_CAPABILITY = 15,
  PDU_SESSION_APPLICATION_ERROR_NO_EPS_5GS_CONTINUITY = 16,
  PDU_SESSION_APPLICATION_ERROR_UNABLE_TO_PAGE_UE = 17,
  PDU_SESSION_APPLICATION_ERROR_UE_NOT_RESPONDING = 18,
  PDU_SESSION_APPLICATION_ERROR_REJECTED_BY_UE = 19,
  PDU_SESSION_APPLICATION_ERROR_REJECTED_DUE_VPLMN_POLICY = 20,
  PDU_SESSION_APPLICATION_ERROR_HO_TAU_IN_PROGRESS = 21,
  PDU_SESSION_APPLICATION_ERROR_INTEGRITY_PROTECTED_MDR_NOT_ACCEPTABLE = 22,
  PDU_SESSION_APPLICATION_ERROR_EBI_EXHAUSTED = 23,
  PDU_SESSION_APPLICATION_ERROR_EBI_REJECTED_LOCAL_POLICY = 24,
  PDU_SESSION_APPLICATION_ERROR_EBI_REJECTED_NO_N26 = 25,
  PDU_SESSION_APPLICATION_ERROR_DEFAULT_EPS_BEARER_INACTIVE = 26,
  PDU_SESSION_APPLICATION_ERROR_HANDOVER_RESOURCE_ALLOCATION_FAILURE = 27,
  PDU_SESSION_APPLICATION_ERROR_CONTEXT_NOT_FOUND = 28,
  PDU_SESSION_APPLICATION_ERROR_INSUFFICIENT_RESOURCES_SLICE = 29,
  PDU_SESSION_APPLICATION_ERROR_INSUFFICIENT_RESOURCES_SLICE_DNN = 30,
  PDU_SESSION_APPLICATION_ERROR_DNN_CONGESTION = 31,
  PDU_SESSION_APPLICATION_ERROR_S_NSSAI_CONGESTION = 32,
  PDU_SESSION_APPLICATION_ERROR_PEER_NOT_RESPONDING = 33,
  PDU_SESSION_APPLICATION_ERROR_NETWORK_FAILURE = 34
};


static const std::vector<std::string> pdu_session_application_error_e2str = {
		"UNKNOWN ERROR",
		"N1_SM_ERROR",
		"SNSSAI_DENIED",
		"DNN_DENIED",
		"PDUTYPE_DENIED",
		"SSC_DENIED",
		"SUBSCRIPTION_DENIED",
		"DNN_NOT_SUPPORTED",
		"PDUTYPE_NOT_SUPPORTED",
		"SSC_NOT_SUPPORTED",
		"HOME_ROUTED_ROAMING_REQUIRED",
		"OUT_OF_LADN_SERVICE_AREA",
		"N2_SM_ERROR",
		"PRIORITIZED_SERVICES_ONLY",
		"PDU_SESSION_ANCHOR_CHANGE",
		"TARGET_MME_CAPABILITY",
		"NO_EPS_5GS_CONTINUITY",
		"UNABLE_TO_PAGE_UE",
		"UE_NOT_RESPONDING",
		"REJECTED_BY_UE",
		"REJECTED_DUE_VPLMN_POLICY",
		"HO_TAU_IN_PROGRESS",
		"INTEGRITY_PROTECTED_MDR_NOT_ACCEPTABLE",
		"EBI_EXHAUSTED",
		"EBI_REJECTED_LOCAL_POLICY",
		"EBI_REJECTED_NO_N26",
		"DEFAULT_EPS_BEARER_INACTIVE",
		"HANDOVER_RESOURCE_ALLOCATION_FAILURE",
		"CONTEXT_NOT_FOUND",
		"INSUFFICIENT_RESOURCES_SLICE",
		"INSUFFICIENT_RESOURCES_SLICE_DNN",
		"DNN_CONGESTION",
		"S_NSSAI_CONGESTION",
		"PEER_NOT_RESPONDING",
		"NETWORK_FAILURE"
};



#endif
