/**
* Nsmf_PDUSession
* SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this file
 * except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */


#include "IndividualSMContextApiImpl.h"
namespace oai {
namespace smf_server {
namespace api {

using namespace oai::smf_server::model;

IndividualSMContextApiImpl::IndividualSMContextApiImpl(std::shared_ptr<Pistache::Rest::Router> rtr,  smf::smf_app *smf_app_inst, std::string address)
    : IndividualSMContextApi(rtr), m_smf_app(smf_app_inst), m_address(address)
    { }

void IndividualSMContextApiImpl::release_sm_context(const std::string &smContextRef, const SmContextReleaseData &smContextReleaseData, Pistache::Http::ResponseWriter &response) {
	Logger::smf_api_server().info("release_sm_context...");
	response.send(Pistache::Http::Code::Ok, "Release_sm_context API has not been implemented yet!\n");
}

void IndividualSMContextApiImpl::retrieve_sm_context(const std::string &smContextRef, const SmContextRetrieveData &smContextRetrieveData, Pistache::Http::ResponseWriter &response) {
	Logger::smf_api_server().info("retrieve_sm_context...");
	response.send(Pistache::Http::Code::Ok, "Retrieve_sm_context API has not been implemented yet!\n");
}

void IndividualSMContextApiImpl::update_sm_context(const std::string &smContextRef, const SmContextUpdateData &smContextUpdateData, Pistache::Http::ResponseWriter &response) {
	//handle Nsmf_PDUSession_UpdateSMContext Request
	Logger::smf_api_server().info("Received a PDUSession_UpdateSMContext Request from AMF.");
	//Get the SmContextUpdateData from this message and process in smf_app
	smf::pdu_session_update_sm_context_request sm_context_req_msg = {};

	std::string n2_sm_information = (smContextUpdateData.getN2SmInfo()).getContentId();
	std::string n2_sm_msg_hex;
	m_smf_app->convert_string_2_hex(n2_sm_information, n2_sm_msg_hex);
	Logger::smf_api_server().debug("smContextMessage, n2 sm information %s",n2_sm_information.c_str());

	std::string n2_sm_info_type = smContextUpdateData.getN2SmInfoType();
	sm_context_req_msg.set_n2_sm_information(n2_sm_msg_hex);
	sm_context_req_msg.set_n2_sm_info_type(n2_sm_info_type);

	//Step 2. TODO: initialize necessary values for sm context req from smContextUpdateData

	//Step 3. Handle the itti_n11_update_sm_context_request message in smf_app
	std::shared_ptr<itti_n11_update_sm_context_request> itti_msg = std::make_shared<itti_n11_update_sm_context_request>(TASK_SMF_N11, TASK_SMF_APP, response, smContextRef);
	itti_msg->req = sm_context_req_msg;
	itti_msg->scid = smContextRef;
	m_smf_app->handle_amf_msg(itti_msg);


}

}
}
}

