/**
 * Nsmf_PDUSession
 * SMF PDU Session Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PDUSessionsCollectionApiImpl.h
 *
 *
 */

#ifndef PDU_SESSIONS_COLLECTION_API_IMPL_H_
#define PDU_SESSIONS_COLLECTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <PDUSessionsCollectionApi.h>

#include <pistache/optional.h>

#include "PduSessionCreateData.h"
#include "PduSessionCreateError.h"
#include "PduSessionCreatedData.h"
#include "ProblemDetails.h"
#include "smf_app.hpp"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::smf_server::model;

class PDUSessionsCollectionApiImpl :
    public oai::smf_server::api::PDUSessionsCollectionApi {
 public:
  PDUSessionsCollectionApiImpl(std::shared_ptr<Pistache::Rest::Router>,
                               smf::smf_app *smf_app_inst, std::string address);
  ~PDUSessionsCollectionApiImpl() {
  }

  void post_pdu_sessions(const PduSessionCreateData &pduSessionCreateData,
                         Pistache::Http::ResponseWriter &response);
 private:
  smf::smf_app *m_smf_app;
  std::string m_address;
};

}
}
}

#endif
