/**
* Nsmf_EventExposure
* Session Management Event Exposure Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.0.alpha-1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "SubscriptionsCollectionApiImpl.h"

namespace oai {
namespace smf_server {
namespace api {

using namespace oai::smf_server::model;

SubscriptionsCollectionApiImpl::SubscriptionsCollectionApiImpl(
    std::shared_ptr<Pistache::Rest::Router> rtr, smf::smf_app *smf_app_inst,
    std::string address)
    :
    SubscriptionsCollectionApi(rtr),
    m_smf_app(smf_app_inst),
    m_address(address) {
}

void SubscriptionsCollectionApiImpl::create_individual_subcription(const NsmfEventExposure &nsmfEventExposure, Pistache::Http::ResponseWriter &response) {
    Logger::smf_api_server().info("SubscriptionsCollectionApiImpl::create_individual_subcription...");
    response.send(Pistache::Http::Code::Not_Implemented,
                  "create_individual_subcription API has not been implemented yet!\n");
}

}
}
}

